import type { SmartCollection, AssetRecord, CollectionType } from "./types.js";

const DEFAULT_COLLECTIONS: Array<{ name: string; type: CollectionType; description: string }> = [
  { name: "Brain", type: "concept", description: "Neuroscience and cognitive imagery" },
  { name: "Space", type: "concept", description: "Cosmic and astronomical visuals" },
  { name: "Universe", type: "concept", description: "Philosophical and existential imagery" },
  { name: "History", type: "theme", description: "Historical and archival visuals" },
  { name: "Philosophy", type: "theme", description: "Philosophical concepts and symbolism" },
  { name: "Emotion", type: "emotion", description: "Emotional and expressive visuals" },
  { name: "Childhood", type: "theme", description: "Memory and early life imagery" },
  { name: "Fear", type: "emotion", description: "Fear and anxiety related visuals" },
  { name: "Future", type: "theme", description: "Futuristic and speculative imagery" },
  { name: "Technology", type: "theme", description: "Science and technology visuals" },
];

export class SmartCollectionManager {
  private collections = new Map<string, SmartCollection>();

  constructor() {
    for (const c of DEFAULT_COLLECTIONS) {
      this.createCollection(c.name, c.type, c.description, true);
    }
  }

  createCollection(name: string, type: CollectionType, description: string, autoGenerated = false): SmartCollection {
    if (!name) throw new Error("Collection name is required");

    const id = this.generateId(name);
    const collection: SmartCollection = {
      id,
      name,
      type,
      description: description ?? "",
      assetIds: [],
      autoGenerated,
      createdAt: new Date().toISOString(),
    };
    this.collections.set(id, collection);
    return collection;
  }

  autoCategorize(asset: AssetRecord): string[] {
    if (!asset || !asset.assetId) return [];

    const assigned: string[] = [];

    for (const [, collection] of this.collections) {
      const match = this.evaluateMatch(asset, collection);
      if (match > 0.3) {
        if (!collection.assetIds.includes(asset.assetId)) {
          collection.assetIds.push(asset.assetId);
        }
        assigned.push(collection.id);
      }
    }

    return assigned;
  }

  getCollection(id: string): SmartCollection | undefined {
    return this.collections.get(id);
  }

  getCollectionsByType(type: CollectionType): SmartCollection[] {
    return Array.from(this.collections.values()).filter((c) => c.type === type);
  }

  getAllCollections(): SmartCollection[] {
    return Array.from(this.collections.values());
  }

  removeAssetFromAll(assetId: string): void {
    if (!assetId) return;
    for (const [, collection] of this.collections) {
      const idx = collection.assetIds.indexOf(assetId);
      if (idx >= 0) collection.assetIds.splice(idx, 1);
    }
  }

  private generateId(name: string): string {
    return `col_${name.toLowerCase().replace(/[^a-z0-9]/g, "_")}`;
  }

  private evaluateMatch(asset: AssetRecord, collection: SmartCollection): number {
    const nameLower = collection.name.toLowerCase();
    const tags = (asset.tags ?? []).map((t) => (t ?? "").toLowerCase());
    const metadata = asset.metadata ?? {} as AssetRecord["metadata"];

    if (tags.some((t) => t.includes(nameLower))) return 0.8;
    if ((metadata.style ?? "").toLowerCase().includes(nameLower)) return 0.6;

    const concepts = [metadata.project, metadata.channel, ...tags].filter(Boolean);
    if (concepts.some((c) => c.toLowerCase().includes(nameLower))) return 0.5;

    return 0;
  }
}
