export type AssetStatus = "generated" | "analyzed" | "indexed" | "approved" | "reused" | "archived";

export type CollectionType = "concept" | "theme" | "emotion" | "symbol" | "character" | "environment" | "style";

export type SearchMethod = "keyword" | "semantic" | "visual" | "concept" | "emotion" | "prompt" | "style" | "character";

export type DuplicateType = "exact" | "near_duplicate" | "composition" | "prompt" | "concept";

export type AssetHealthCategory = "quality" | "resolution" | "sharpness" | "style_consistency" | "reuse_value";

export interface AssetRecord {
  assetId: string;
  imageData: string;
  thumbnailData: string;
  embedding: number[];
  prompt: string;
  negativePrompt: string;
  visualDNA: Record<string, string>;
  motionMetadata: Record<string, unknown>;
  projectHistory: string[];
  versionHistory: AssetVersion[];
  currentVersion: number;
  status: AssetStatus;
  qualityScore: number;
  reuseCount: number;
  lastUsed: string | null;
  totalScreenTime: number;
  averageHoldDuration: number;
  createdAt: string;
  channelId: string;
  isFavorite: boolean;
  collections: string[];
  tags: string[];
  metadata: AssetMetadata;
}

export interface AssetVersion {
  version: number;
  change: string;
  timestamp: string;
  previousImageData?: string;
}

export interface AssetMetadata {
  generationDate: string;
  project: string;
  channel: string;
  promptVersion: string;
  model: string;
  aspectRatio: string;
  seed: number;
  style: string;
  qualityScore: number;
  motionCompatibility: string[];
  lastUsed: string | null;
  reuseCount: number;
  healthScores: Record<AssetHealthCategory, number>;
  overallHealth: number;
}

export interface SmartCollection {
  id: string;
  name: string;
  type: CollectionType;
  description: string;
  assetIds: string[];
  autoGenerated: boolean;
  createdAt: string;
}

export interface AssetSearchQuery {
  method: SearchMethod;
  query: string;
  imageQuery?: string;
  channelId?: string;
  status?: AssetStatus;
  minQuality?: number;
  tags?: string[];
  collections?: string[];
}

export interface AssetSearchResult {
  asset: AssetRecord;
  score: number;
  matchedOn: string[];
}

export interface DuplicateReport {
  type: DuplicateType;
  sourceAssetId: string;
  matchAssetId: string;
  confidence: number;
  reason: string;
}

export interface AssetHealthReport {
  assetId: string;
  quality: number;
  resolution: number;
  sharpness: number;
  styleConsistency: number;
  reuseValue: number;
  overallHealth: number;
  needsRegeneration: boolean;
}

export interface ReuseHistoryEntry {
  projectId: string;
  sceneId: string;
  duration: number;
  holdDuration: number;
  motionApplied: string;
  usedAt: string;
}

export interface AssetCacheEntry<T> {
  key: string;
  data: T;
  createdAt: string;
  ttl: number;
}

export interface StorageStructure {
  assetDb: Map<string, AssetRecord>;
  metadataDb: Map<string, AssetMetadata>;
  embeddingDb: Map<string, number[]>;
  thumbnailCache: Map<string, string>;
  originalStorage: Map<string, string>;
  backupStorage: Map<string, string>;
  collections: Map<string, SmartCollection>;
}

export interface RecommendationFactor {
  factor: string;
  score: number;
  weight: number;
  weightedScore: number;
}

export interface AssetRecommendation {
  asset: AssetRecord;
  confidence: number;
  factors: RecommendationFactor[];
  reason: string;
}
